-- ─────────────────────────────────────────────────────────────────────────────
-- Flyway baseline (2026-09-01)
--
-- This is a `pg_dump --schema-only` of the schema Hibernate's ddl-auto=update had
-- already built from the JPA entities as of this commit — it is not a hand-written
-- migration. It exists so Flyway has a V1 to baseline an already-populated database
-- against (spring.flyway.baseline-on-migrate=true): on a DB that already has these
-- tables, Flyway records V1 as already-applied without re-running it; on an empty
-- DB (fresh local/CI setup) it runs for real and creates everything from scratch.
--
-- ddl-auto=update is still on in every profile after this — Flyway takes over
-- tracking future schema changes as versioned migrations, but the automatic
-- Hibernate pass that already runs on every boot is left in place for now. Turning
-- it off is a separate, deliberate follow-up once Flyway has proven itself.
-- ─────────────────────────────────────────────────────────────────────────────

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.19
-- Dumped by pg_dump version 15.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: car_setups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.car_setups (
    id bigint NOT NULL,
    brake_bias real NOT NULL,
    diff_off_throttle integer NOT NULL,
    diff_on_throttle integer NOT NULL,
    front_wing_angle real NOT NULL,
    rear_wing_angle real NOT NULL,
    suspension_stiffness real NOT NULL,
    tyre_pressure_front real NOT NULL,
    tyre_pressure_rear real NOT NULL,
    race_id bigint,
    team_id bigint
);


--
-- Name: car_setups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.car_setups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_setups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: championships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.championships (
    id bigint NOT NULL,
    leader_name character varying(255),
    leader_points real NOT NULL,
    p2_gap real NOT NULL,
    p3_gap real NOT NULL,
    season integer NOT NULL,
    type character varying(255),
    CONSTRAINT championships_type_check CHECK (((type)::text = ANY ((ARRAY['DRIVERS'::character varying, 'CONSTRUCTORS'::character varying])::text[])))
);


--
-- Name: championships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.championships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.championships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuit_geometry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuit_geometry (
    id bigint NOT NULL,
    elevation_gainm real,
    elevation_maxm real,
    elevation_minm real,
    fetched_at timestamp(6) with time zone,
    measured_length_km real,
    openf1_driver_number integer,
    openf1_lap_number integer,
    openf1_session_key integer,
    point_count integer NOT NULL,
    points text,
    samples text,
    source character varying(255) NOT NULL,
    spanxm real,
    spanzm real,
    circuit_id bigint,
    CONSTRAINT circuit_geometry_source_check CHECK (((source)::text = ANY ((ARRAY['OPENF1'::character varying, 'GEOJSON'::character varying, 'SYNTHETIC'::character varying])::text[])))
);


--
-- Name: circuit_geometry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuit_geometry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuit_geometry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuits (
    id bigint NOT NULL,
    city character varying(255),
    country character varying(255) NOT NULL,
    lap_record_holder character varying(255),
    lap_record_sec real NOT NULL,
    length_km real NOT NULL,
    name character varying(255) NOT NULL,
    total_laps integer NOT NULL,
    turn_count integer NOT NULL,
    type character varying(255),
    direction character varying(255),
    drs_zones integer,
    elevation_gainm real,
    first_gp_year integer,
    latitude double precision,
    longitude double precision,
    CONSTRAINT circuits_direction_check CHECK (((direction)::text = ANY ((ARRAY['CLOCKWISE'::character varying, 'ANTI_CLOCKWISE'::character varying])::text[]))),
    CONSTRAINT circuits_type_check CHECK (((type)::text = ANY ((ARRAY['PERMANENT'::character varying, 'STREET'::character varying, 'OVAL'::character varying, 'HYBRID'::character varying])::text[])))
);


--
-- Name: circuits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_contracts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.driver_contracts (
    id bigint NOT NULL,
    annual_salarym real NOT NULL,
    end_date date,
    has_option_year boolean NOT NULL,
    start_date date,
    status character varying(255),
    driver_id bigint,
    CONSTRAINT driver_contracts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'TERMINATED'::character varying, 'OPTION_YEAR'::character varying, 'NEGOTIATING'::character varying])::text[])))
);


--
-- Name: driver_contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.driver_contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    car_number integer NOT NULL,
    career_points integer NOT NULL,
    career_poles integer NOT NULL,
    career_wins integer NOT NULL,
    date_of_birth date,
    name character varying(255) NOT NULL,
    nationality character varying(255),
    team_id bigint,
    CONSTRAINT drivers_car_number_check CHECK (((car_number <= 99) AND (car_number >= 1)))
);


--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: engineers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.engineers (
    id bigint NOT NULL,
    name character varying(255),
    nationality character varying(255),
    specialization character varying(255),
    team_id bigint
);


--
-- Name: engineers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.engineers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.engineers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.incidents (
    id bigint NOT NULL,
    description character varying(255),
    lap integer NOT NULL,
    safety_car_laps integer NOT NULL,
    type character varying(255),
    race_id bigint,
    CONSTRAINT incidents_type_check CHECK (((type)::text = ANY ((ARRAY['SAFETY_CAR'::character varying, 'VIRTUAL_SAFETY_CAR'::character varying, 'RED_FLAG'::character varying, 'YELLOW_FLAG'::character varying, 'COLLISION'::character varying, 'MECHANICAL_FAILURE'::character varying])::text[])))
);


--
-- Name: incidents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.incidents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lap_telemetry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lap_telemetry (
    id bigint NOT NULL,
    brake_pct real NOT NULL,
    drs_active boolean NOT NULL,
    fuel_load real NOT NULL,
    gear integer NOT NULL,
    lap_number integer NOT NULL,
    lap_time_sec real NOT NULL,
    rpm integer NOT NULL,
    speed_kmh real NOT NULL,
    throttle_pct real NOT NULL,
    race_result_id bigint,
    tyre_compound_id bigint
);


--
-- Name: lap_telemetry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lap_telemetry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lap_telemetry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: live_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.live_positions (
    id bigint NOT NULL,
    driver_number integer NOT NULL,
    "position" integer NOT NULL,
    session_key integer NOT NULL,
    "timestamp" timestamp(6) with time zone
);


--
-- Name: live_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.live_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.live_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    icon character varying(255),
    message character varying(255),
    read boolean NOT NULL,
    title character varying(255),
    type character varying(255)
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_tokens (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    used boolean NOT NULL,
    CONSTRAINT otp_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['FORGOT_PASSWORD'::character varying, 'LOGIN_OTP'::character varying, 'OAUTH_2FA'::character varying])::text[])))
);


--
-- Name: otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: penalties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.penalties (
    id bigint NOT NULL,
    grid_drop integer NOT NULL,
    lap integer NOT NULL,
    reason character varying(255),
    time_seconds integer NOT NULL,
    type character varying(255),
    driver_id bigint,
    race_id bigint,
    CONSTRAINT penalties_type_check CHECK (((type)::text = ANY ((ARRAY['TIME_5S'::character varying, 'TIME_10S'::character varying, 'TIME_20S'::character varying, 'DRIVE_THROUGH'::character varying, 'STOP_GO'::character varying, 'GRID_DROP'::character varying, 'DISQUALIFIED'::character varying, 'REPRIMAND'::character varying])::text[])))
);


--
-- Name: penalties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.penalties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penalties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pit_stops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pit_stops (
    id bigint NOT NULL,
    crew_size integer NOT NULL,
    duration_sec real NOT NULL,
    lap_number integer NOT NULL,
    tyre_in character varying(255),
    tyre_out character varying(255),
    under_safety_car boolean NOT NULL,
    race_result_id bigint,
    tyre_compound_id bigint,
    CONSTRAINT pit_stops_tyre_in_check CHECK (((tyre_in)::text = ANY ((ARRAY['SOFT'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INTERMEDIATE'::character varying, 'WET'::character varying])::text[]))),
    CONSTRAINT pit_stops_tyre_out_check CHECK (((tyre_out)::text = ANY ((ARRAY['SOFT'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INTERMEDIATE'::character varying, 'WET'::character varying])::text[])))
);


--
-- Name: pit_stops_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pit_stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pit_stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qualifying_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qualifying_results (
    id bigint NOT NULL,
    best_time double precision,
    eliminated_q1 boolean NOT NULL,
    eliminated_q2 boolean NOT NULL,
    grid_position integer NOT NULL,
    q1_position integer NOT NULL,
    q1_time double precision,
    q2_position integer NOT NULL,
    q2_time double precision,
    q3_position integer NOT NULL,
    q3_time double precision,
    qualifying_position integer NOT NULL,
    driver_id bigint,
    race_id bigint
);


--
-- Name: qualifying_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.qualifying_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qualifying_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: race_news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.race_news (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    tag character varying(255),
    title character varying(255) NOT NULL,
    race_id bigint NOT NULL
);


--
-- Name: race_news_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.race_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.race_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: race_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.race_results (
    id bigint NOT NULL,
    dnf_reason character varying(255),
    fastest_lap_number integer NOT NULL,
    fastest_lap_time real NOT NULL,
    finish_position integer NOT NULL,
    has_fastest_lap boolean NOT NULL,
    points real NOT NULL,
    start_position integer NOT NULL,
    driver_id bigint,
    race_id bigint,
    team_id bigint
);


--
-- Name: race_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.race_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.race_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: races; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.races (
    id bigint NOT NULL,
    date date NOT NULL,
    name character varying(255) NOT NULL,
    round_number integer NOT NULL,
    season integer NOT NULL,
    status character varying(255) NOT NULL,
    circuit_id bigint,
    CONSTRAINT races_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'RED_FLAGGED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: races_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.races ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.races_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sponsorships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sponsorships (
    id bigint NOT NULL,
    category character varying(255),
    end_date date,
    logo_url character varying(255),
    sponsor_name character varying(255),
    start_date date,
    valuem real NOT NULL,
    team_id bigint
);


--
-- Name: sponsorships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sponsorships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sponsorships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: strategy_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_plans (
    id bigint NOT NULL,
    executed boolean NOT NULL,
    notes character varying(255),
    pit_lap1 integer NOT NULL,
    pit_lap2 integer NOT NULL,
    pit_lap3 integer NOT NULL,
    pit_laps_json character varying(255),
    plan_name character varying(255),
    planned_compounds character varying(255),
    planned_stops integer NOT NULL,
    engineer_id bigint,
    race_id bigint,
    stints_json text
);


--
-- Name: strategy_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.strategy_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.strategy_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    annual_budgetm real NOT NULL,
    base character varying(255),
    championships integer NOT NULL,
    color_hex character varying(255),
    country character varying(255),
    founded_year integer NOT NULL,
    name character varying(255) NOT NULL,
    accent_hex character varying(255),
    car_name character varying(255),
    engine_supplier character varying(255),
    team_principal character varying(255)
);


--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tyre_compounds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tyre_compounds (
    id bigint NOT NULL,
    degradation_rate real NOT NULL,
    max_laps integer NOT NULL,
    name character varying(255),
    optimal_temp_max real NOT NULL,
    optimal_temp_min real NOT NULL,
    type character varying(255),
    CONSTRAINT tyre_compounds_type_check CHECK (((type)::text = ANY ((ARRAY['SOFT'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INTERMEDIATE'::character varying, 'WET'::character varying])::text[])))
);


--
-- Name: tyre_compounds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tyre_compounds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tyre_compounds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(500),
    bio character varying(300),
    created_at timestamp(6) without time zone,
    date_of_birth date,
    display_name character varying(100),
    email character varying(255) NOT NULL,
    is_active boolean,
    location character varying(100),
    password character varying(255) NOT NULL,
    phone character varying(20),
    role character varying(255) NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'ENGINEER'::character varying, 'VIEWER'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weather_conditions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weather_conditions (
    id bigint NOT NULL,
    air_tempc real NOT NULL,
    condition character varying(255),
    humidity_pct real NOT NULL,
    session character varying(255),
    track_tempc real NOT NULL,
    wind_speed_kmh real NOT NULL,
    race_id bigint,
    CONSTRAINT weather_conditions_condition_check CHECK (((condition)::text = ANY ((ARRAY['DRY'::character varying, 'DAMP'::character varying, 'WET'::character varying, 'MIXED'::character varying, 'STORMY'::character varying])::text[])))
);


--
-- Name: weather_conditions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.weather_conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: car_setups car_setups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.car_setups
    ADD CONSTRAINT car_setups_pkey PRIMARY KEY (id);


--
-- Name: championships championships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.championships
    ADD CONSTRAINT championships_pkey PRIMARY KEY (id);


--
-- Name: circuit_geometry circuit_geometry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_geometry
    ADD CONSTRAINT circuit_geometry_pkey PRIMARY KEY (id);


--
-- Name: circuits circuits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits
    ADD CONSTRAINT circuits_pkey PRIMARY KEY (id);


--
-- Name: driver_contracts driver_contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver_contracts
    ADD CONSTRAINT driver_contracts_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: engineers engineers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.engineers
    ADD CONSTRAINT engineers_pkey PRIMARY KEY (id);


--
-- Name: incidents incidents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT incidents_pkey PRIMARY KEY (id);


--
-- Name: lap_telemetry lap_telemetry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lap_telemetry
    ADD CONSTRAINT lap_telemetry_pkey PRIMARY KEY (id);


--
-- Name: live_positions live_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.live_positions
    ADD CONSTRAINT live_positions_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: otp_tokens otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT otp_tokens_pkey PRIMARY KEY (id);


--
-- Name: penalties penalties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penalties
    ADD CONSTRAINT penalties_pkey PRIMARY KEY (id);


--
-- Name: pit_stops pit_stops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_stops
    ADD CONSTRAINT pit_stops_pkey PRIMARY KEY (id);


--
-- Name: qualifying_results qualifying_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualifying_results
    ADD CONSTRAINT qualifying_results_pkey PRIMARY KEY (id);


--
-- Name: race_news race_news_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_news
    ADD CONSTRAINT race_news_pkey PRIMARY KEY (id);


--
-- Name: race_results race_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_results
    ADD CONSTRAINT race_results_pkey PRIMARY KEY (id);


--
-- Name: races races_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.races
    ADD CONSTRAINT races_pkey PRIMARY KEY (id);


--
-- Name: sponsorships sponsorships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sponsorships
    ADD CONSTRAINT sponsorships_pkey PRIMARY KEY (id);


--
-- Name: strategy_plans strategy_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_plans
    ADD CONSTRAINT strategy_plans_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: tyre_compounds tyre_compounds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tyre_compounds
    ADD CONSTRAINT tyre_compounds_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: teams uka510no6sjwqcx153yd5sm4jrr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT uka510no6sjwqcx153yd5sm4jrr UNIQUE (name);


--
-- Name: circuit_geometry uknrhtxw5jnst69s99crpygkhvn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_geometry
    ADD CONSTRAINT uknrhtxw5jnst69s99crpygkhvn UNIQUE (circuit_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: drivers ukr4fnguaxrfb4rtqwj3ql006ug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukr4fnguaxrfb4rtqwj3ql006ug UNIQUE (car_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: weather_conditions weather_conditions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weather_conditions
    ADD CONSTRAINT weather_conditions_pkey PRIMARY KEY (id);


--
-- Name: strategy_plans fk1qmykv5amiqv420wkr8ubmxuc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_plans
    ADD CONSTRAINT fk1qmykv5amiqv420wkr8ubmxuc FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: race_results fk2elke3gjhe8xwitsftgj573cn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_results
    ADD CONSTRAINT fk2elke3gjhe8xwitsftgj573cn FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: penalties fk31mefrvjns0pqldeofdrbq79o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penalties
    ADD CONSTRAINT fk31mefrvjns0pqldeofdrbq79o FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: engineers fk38b7a4sp7w08bwnrmwqtg2l0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.engineers
    ADD CONSTRAINT fk38b7a4sp7w08bwnrmwqtg2l0b FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: race_news fk5xdnxtrfmfmxw1ik6moy5m1ik; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_news
    ADD CONSTRAINT fk5xdnxtrfmfmxw1ik6moy5m1ik FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: car_setups fk8fuwopwq096byiceyoilnomlx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.car_setups
    ADD CONSTRAINT fk8fuwopwq096byiceyoilnomlx FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: strategy_plans fkbal1dr1ab2vrcocojjddyibk4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_plans
    ADD CONSTRAINT fkbal1dr1ab2vrcocojjddyibk4 FOREIGN KEY (engineer_id) REFERENCES public.engineers(id);


--
-- Name: sponsorships fkbhij2xap2dlb7oynr2epbnnba; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sponsorships
    ADD CONSTRAINT fkbhij2xap2dlb7oynr2epbnnba FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: drivers fkcay8hmpefrncg4apmusc0mkth; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fkcay8hmpefrncg4apmusc0mkth FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: car_setups fkccnmbkv71aqe23wsdneltghv0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.car_setups
    ADD CONSTRAINT fkccnmbkv71aqe23wsdneltghv0 FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: qualifying_results fkdj9j24330x9ovw5vpu3jduywd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualifying_results
    ADD CONSTRAINT fkdj9j24330x9ovw5vpu3jduywd FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: driver_contracts fkdv2ptk25w7o64euyyi6iiu0am; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver_contracts
    ADD CONSTRAINT fkdv2ptk25w7o64euyyi6iiu0am FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: race_results fke9qpq6a12gf5uj6fkhyxi3lej; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_results
    ADD CONSTRAINT fke9qpq6a12gf5uj6fkhyxi3lej FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: qualifying_results fkh41krt5bj3hpglbr391m939u0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualifying_results
    ADD CONSTRAINT fkh41krt5bj3hpglbr391m939u0 FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: penalties fkl9rgqo5avbkv684b5vht6grf4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penalties
    ADD CONSTRAINT fkl9rgqo5avbkv684b5vht6grf4 FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: circuit_geometry fkmkqu46khbgjikganciro08p7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_geometry
    ADD CONSTRAINT fkmkqu46khbgjikganciro08p7m FOREIGN KEY (circuit_id) REFERENCES public.circuits(id);


--
-- Name: lap_telemetry fkmpa40xy8g946vr1s87m4meeig; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lap_telemetry
    ADD CONSTRAINT fkmpa40xy8g946vr1s87m4meeig FOREIGN KEY (race_result_id) REFERENCES public.race_results(id);


--
-- Name: incidents fknfxnu5q0a9tiqw5bl30chisvy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.incidents
    ADD CONSTRAINT fknfxnu5q0a9tiqw5bl30chisvy FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: lap_telemetry fko3ua3kpnuy0qk36s6w4y41qsg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lap_telemetry
    ADD CONSTRAINT fko3ua3kpnuy0qk36s6w4y41qsg FOREIGN KEY (tyre_compound_id) REFERENCES public.tyre_compounds(id);


--
-- Name: pit_stops fko5ow3x43ae7w8wodi231kdpbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_stops
    ADD CONSTRAINT fko5ow3x43ae7w8wodi231kdpbb FOREIGN KEY (tyre_compound_id) REFERENCES public.tyre_compounds(id);


--
-- Name: race_results fkog6c3y9gos90b61bw11f5c0tb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.race_results
    ADD CONSTRAINT fkog6c3y9gos90b61bw11f5c0tb FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: weather_conditions fkq92uj9a6gb851g1tk4c6twaic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weather_conditions
    ADD CONSTRAINT fkq92uj9a6gb851g1tk4c6twaic FOREIGN KEY (race_id) REFERENCES public.races(id);


--
-- Name: races fksmryk5wkwqwa2wukhuv7amoab; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.races
    ADD CONSTRAINT fksmryk5wkwqwa2wukhuv7amoab FOREIGN KEY (circuit_id) REFERENCES public.circuits(id);


--
-- Name: pit_stops fktqo5c95e3itoina5o1e786s5d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_stops
    ADD CONSTRAINT fktqo5c95e3itoina5o1e786s5d FOREIGN KEY (race_result_id) REFERENCES public.race_results(id);


--
-- PostgreSQL database dump complete
--


