-- Who did what in the admin panel: user/role/password changes and the data-repair endpoints.
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor      varchar(50)  NOT NULL,
    action     varchar(64)  NOT NULL,
    target     varchar(255),
    detail     varchar(500),
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON admin_audit_log (created_at DESC);
